# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18443ea677b248ad6182017799bdee8a058b5f6a2b6aa7501e4db4051697a2010c648ebc02b01249da45cd722812a02e35117def1b4f21263163a4826415b421

test:
  secret_key_base: 5a5b813c00aa29540e360831ef737c551aefe873779dcd0ee80b45f63bc323d774650f09fb8d8d131ea21a13bb541dbcce598a96c1f264d2d7da8341329f719d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
